const PublicationData = [
	{
		title: 'The impact of violating the independence assumption in meta-analysis on biomarker discovery',
		authors: 'Abbas-Aghababazadeh F, Xu W, Haibe-Kains B. Front Genet',
		year: '2023',
		url: 'https://pubmed.ncbi.nlm.nih.gov/36726714/',
		publisher: 'NIH',
		releaseDate: '2023 Jan 4',
		image: 'frontiers.png',
		members: [],
	},
	{
		title: 'Impact of radiotherapy quality assurance on nasopharyngeal carcinoma: Usage of a novel web-based quality assurance application',
		authors: 'Kim JW, Marsilla J, Kazmierski M, Tkachuk D, Huang SH, Xu W, Cho J, Ringash J, Bratman S, Haibe-Kains B, Hope A',
		year: '2023',
		url: 'https://pubmed.ncbi.nlm.nih.gov/36948414/',
		publisher: '',
		releaseDate: '2023 Mar 20',
		image: '',
		members: [],
	},
	{
		title: 'A Machine Learning Challenge for Prognostic Modelling in Head and Neck Cancer Using Multi-modal Data',
		authors: 'Michal Kazmierski, Mattea Welch, Sejin Kim, Chris McIntosh, Princess Margaret Head, Neck Cancer Group, Katrina Rey-McIntyre, Shao Hui Huang, Tirth Patel, Tony Tadic, Michael Milosevic, Fei-Fei Liu, Andrew Hope, Scott Bratman, Benjamin Haibe-Kains',
		year: '2023',
		url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10309070/',
		publisher: '',
		releaseDate: '2023 Jun 29',
		image: '',
		members: [],
	},
	{
		title: 'PharmacoDB 2.0: improving scalability and transparency of in vitro pharmacogenomics analysis',
		authors: 'Feizi N, Nair SK, Smirnov P, Beri G, Eeles C, Esfahani PN, Nakano M, Tkachuk D, Mammoliti A, Gorobets E, Mer AS, Lin E, Yu Y, Martin S, Hafner M, Haibe-Kains B',
		year: '2022',
		url: 'https://pubmed.ncbi.nlm.nih.gov/34850112/',
		publisher: 'NIH',
		releaseDate: '2022 Jan 7',
		image: '',
		members: [],
	},
	{
		title: 'Evaluation of statistical approaches for association testing in noisy drug screening data',
		authors: 'Smirnov P, Smith I, Safikhani Z, Ba-Alawi W, Khodakarami F, Lin E, Yu Y, Martin S, Ortmann J, Aittokallio T, Hafner M, Haibe-Kains B',
		year: '2022',
		url: 'https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-022-04693-z',
		publisher: 'BMC',
		releaseDate: '2022 May 18',
		image: 'BMC_Bioinformatics.jpg',
		members: [],
	},
	{
		title: 'Bimodal gene expression in cancer patients provides interpretable biomarkers for drug sensitivity',
		authors: 'Ba-Alawi W, Kadambat Nair S, Li B, Mammoliti A, Smirnov P, Mer AS, Penn LZ, Haibe-Kains B',
		year: '2022',
		url: 'https://pubmed.ncbi.nlm.nih.gov/35536872/',
		publisher: 'NIH',
		releaseDate: '2022 Jul 5',
		image: '',
		members: [],
	},
	{
		title: 'Leveraging Big Data of Immune Checkpoint Blockade Response Identifies Novel Potential Targets',
		authors: 'Bareche Y, Kelly D, Abbas-Aghababazadeh F, Nakano M, Esfahani PN, Tkachuk D, Mohammad H, Samstein R, Lee CH, Morris LGT, Bedard PL, Haibe-Kains B, Stagg J',
		year: '2022',
		url: 'https://pubmed.ncbi.nlm.nih.gov/36055464/',
		publisher: 'NIH',
		releaseDate: '2022 Aug 30',
		image: '',
		members: [],
	},
	{
		title: 'Computational pharmacogenomic screen identifies drugs that potentiate the anti-breast cancer activity of statins',
		authors: 'van Leeuwen JE, Ba-Alawi W, Branchard E, Cruickshank J, Schormann W, Longo J, Silvester J, Gross PL, Andrews DW, Cescon DW, Haibe-Kains B, Penn LZ, Gendoo DMAA',
		year: '2022',
		url: 'https://pubmed.ncbi.nlm.nih.gov/36948414/',
		publisher: 'NIH',
		releaseDate: '2022 Oct 24',
		image: '',
		members: [],
	},
	{
		title: 'Biological and therapeutic implications of a unique subtype of NPM1 mutated AML',
		authors: 'Mer AS, Heath EM, Madani Tonekaboni SA, Dogan-Artun N, Nair SK, Murison A, Garcia-Prat L, Shlush L, Hurren R, Voisin V, Bader GD, Nislow C, Rantalainen M, Lehmann S, Gower M, Guidos CJ, Lupien M, Dick JE, Minden MD, Schimmer AD, Haibe-Kains B',
		year: '2021',
		url: 'https://pubmed.ncbi.nlm.nih.gov/33594052/',
		publisher: 'Nat Commun',
		releaseDate: '2021 Feb 16',
		image: '',
		members: [],
	},
	{
		title: 'Deep-CR MTLR: a Multi-Modal Approach for Cancer Survival Prediction with Competing Risks',
		authors: 'Sejin Kim, Michal Kazmierski, Benjamin Haibe-Kains',
		year: '2021',
		url: 'https://arxiv.org/abs/2012.05765',
		publisher: '',
		releaseDate: '2021 Mar 22',
		image: 'publ_arxiv.jpg',
		members: [],
	},
	{
		title: 'Orchestrating and sharing large multimodal data for transparent and reproducible research',
		authors: 'Mammoliti A, Smirnov P, Nakano M, Safikhani Z, Eeles C, Seo H, Nair SK, Mer AS, Smith I, Ho C, Beri G, Kusko R; Massive Analysis Quality Control (MAQC) Society Board of Directors, Lin E, Yu Y, Martin S, Hafner M, Haibe-Kains B',
		year: '2021',
		url: 'https://www.nature.com/articles/s41467-021-25974-w',
		publisher: 'Nature',
		releaseDate: '2021 Oct 4',
		image: '',
		members: [],
	},
	{
		title: 'Drug sensitivity prediction from cell line-based pharmacogenomics data: guidelines for developing machine learning models',
		authors: 'Sharifi-Noghabi H, Jahangiri-Tazehkand S, Smirnov P, Hon C, Mammoliti A, Nair SK, Mer AS, Ester M, Haibe-Kains B',
		year: '2021',
		url: 'https://pubmed.ncbi.nlm.nih.gov/34382071/',
		publisher: 'NIH',
		releaseDate: '2021 Nov 5',
		image: '',
		members: [],
	},
	{
		title: 'Assessing therapy response in patient-derived xenografts',
		authors: 'Ortmann J, Rampášek L, Tai E, Mer AS, Shi R, Stewart EL, Mascaux C, Fares A, Pham NA, Beri G, Eeles C, Tkachuk D, Ho C, Sakashita S, Weiss J, Jiang X, Liu G, Cescon DW, O`Brien CA, Guo S, Tsao MS, Haibe-Kains B, Goldenberg A',
		year: '2021',
		url: 'https://pubmed.ncbi.nlm.nih.gov/34788078/',
		publisher: 'NIH',
		releaseDate: '2021 Nov 17',
		image: '',
		members: [],
	},

	{
		title: 'Machine learning approaches to drug response prediction: challenges and recent progress',
		authors: 'Adam G, Rampášek L, Safikhani Z, Smirnov P, Haibe-Kains B*, Goldenberg A',
		year: '2020',
		url: 'https://www.nature.com/articles/s41698-020-0122-1',
		publisher: 'Nature',
		releaseDate: '2020 Jun 15',
		image: '',
		members: [],
	},
	{
		title: 'SYNERGxDB: an integrative pharmacogenomic portal to identify synergistic drug combinations for precision oncology',
		authors: 'Seo H, Tkachuk D, Ho C, Mammoliti A, Rezaie A, Madani Tonekaboni SA, Haibe-Kains B',
		year: '2020',
		url: 'https://academic.oup.com/nar/article/48/W1/W494/5842189',
		publisher: 'Oxford Press',
		releaseDate: '2020 Jul 2',
		image: '',
		members: [],
	},

	{
		title: 'ToxicoDB: an integrated database to mine and visualize large-scale toxicogenomic datasets',
		authors: 'Nair SK, Eeles C, Ho C, Beri G, Yoo E, Tkachuk D, Tang A, Nijrabi P, Smirnov P, Seo H, Jennen D, Haibe-Kains B',
		year: '2020',
		url: 'https://pubmed.ncbi.nlm.nih.gov/32421831/',
		publisher: 'Nucleic Acids Res',
		releaseDate: '2020 Jul 2',
		image: '',
		members: [],
	},
	{
		title: 'Transparency and reproducibility in artificial intelligence',
		authors: ' Haibe-Kains B, Adam GA, Hosny A, Khodakarami F; Massive Analysis Quality Control Society Board of Directors, Waldron L, Wang B, McIntosh C, Goldenberg A, Kundaje A, Greene CS, Broderick T, Hoffman MM, Leek JT, Korthauer K, Huber W, Brazma A, Pineau J, Tibshirani R, Hastie T, Ioannidis JPA, Quackenbush J, Aerts HJWL',
		year: '2020',
		url: 'https://www.nature.com/articles/s41586-020-2766-y',
		publisher: 'Nature',
		releaseDate: '2020 Oct 14',
		image: '',
		members: [],
	},
	{
		title: 'Assessment of Genetic Drift in Large Pharmacogenomic Studies',
		authors: 'Quevedo R, Smirnov P, Tkachuk D, Ho C, El-Hachem N, Safikhani Z, Pugh TJ, Haibe-Kains B',
		year: '2020',
		url: 'https://pubmed.ncbi.nlm.nih.gov/32937114/',
		publisher: 'Cell Syst',
		releaseDate: '2020 Oct 21',
		image: '',
		members: [],
	},
	{
		title: 'Whole Genomes Define Concordance of Matched Primary, Xenograft, and Organoid Models of Pancreas Cancer',
		authors: 'Gendoo DMA, Denroche RE, Zhang A, Jang GH, Lemire M, Fischer S, Radulovich N, Chadwick D, Lungu LM, Stein LD, Wilson JM, Bartlett JMS, Tsao MS, Dhani N, Hedley D, Gallinger S, Haibe-Kains B',
		year: '2019',
		url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6328084/',
		publisher: 'Plos Compute Biol',
		releaseDate: '2019 Jan 10',
		image: 'plos_biology.png',
		members: [],
	},
	{
		title: 'Integrative pharmacogenomics analysis of patient-derived xenografts',
		authors: 'Mer AS, Ba-Alawi W, Smirnov P, Wang YX, Brew B, Ortmann J, Tsao MS, Cescon DW, Goldenberg A, Haibe-Kains B',
		year: '2019',
		url: 'https://pubmed.ncbi.nlm.nih.gov/31142512/',
		publisher: '',
		releaseDate: '2019 May 29',
		image: 'cancer_res_101158.jpg',
		members: [],
	},
	{
		title: 'Meta-Analysis of 1,200 Transcriptomic Profiles Identifies a Prognostic Model for Pancreatic Ductal Adenocarcinoma',
		authors: 'Sandhu V, Labori KJ, Borgida A, Lungu I, Bartlett J, Hafezi-Bakhtiari S, Denroche RE, Jang GH, Pasternack D, Mbaabali F, Watson M, Wilson J, Kure EH, Gallinger S, Haibe-Kains B',
		year: '2019',
		url: 'https://aacrjournals.org/cancerres/article/79/17/4539/638195/Integrative-Pharmacogenomics-Analysis-of-Patient',
		publisher: 'Cancer Research',
		releaseDate: '2019 May',
		image: 'cancer_res_101158.jpg',
		members: [],
	},
	{
		title: 'Identifying clusters of cis-regulatory elements underpinning TAD structures and lineage-specific regulatory networks',
		authors: 'Madani Tonekaboni SA, Mazrooei P, Kofia V, Haibe-Kains B*, Lupien M*',
		year: '2019',
		url: 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6771399/',
		publisher: 'Genome Res',
		releaseDate: '2019 Oct 29',
		image: 'genome_research.jpg',
		members: [],
	},
	{
		title: 'Modeling cellular response in large-scale radiogenomic databases to advance precision radiotherapy',
		authors: 'Manem VS, Lambie M, Smith I, Smirnov P, Kofia V, Freeman M, Koritzinsky M, Abazeed ME, Haibe-Kains B, Bratman SV',
		year: '2019',
		url: 'https://pubmed.ncbi.nlm.nih.gov/31558563/',
		publisher: 'Cancer Res',
		releaseDate: '2019 Dec 15',
		image: 'cancer_res_101158.jpg',
		members: [],
	},

	{
		title: 'PharmacoDB: an integrative database for mining in vitro anticancer drug screening studies',
		authors: 'Smirnov P, Kofia V, Maru A, Freeman M, Ho C, El-Hachem N, Adam GA, Ba-alawi W, Safikhani Z, Haibe-Kains B',
		year: '2018',
		url: 'https://academic.oup.com/nar/article/46/D1/D994/4372597',
		publisher: 'Nucleic Acids Research',
		releaseDate: '2018 Jan 4',
		image: '',
		members: [],
	},
	{
		title: 'CrosstalkNet: A Visualization tool for differential co-expression networks and communities',
		authors: 'Manem VSK, Adam GA, Gruosso T, Mathieu Gigoux M, Bertos N, Park M, Haibe-Kains B',
		year: '2018',
		url: 'https://pubmed.ncbi.nlm.nih.gov/29459407/',
		publisher: 'Cancer Res',
		releaseDate: '2018 Apr 15',
		image: '',
		members: [],
	},
	{
		title: 'Consensus on Molecular Subtypes of Ovarian Cancer',
		authors: 'Chen GM, Kannan L,  Geistlinger L,  Kofia V,  Safikhani Z, Gendoo DMA,  Parmigiani G, Birrer M,  Haibe-Kains B',
		year: '2018',
		url: 'https://pubmed.ncbi.nlm.nih.gov/30084834/',
		publisher: 'Clin Cancer Res',
		releaseDate: '2018 Oct 15',
		image: '',
		members: [],
	},

	{
		title: 'Integrative cancer pharmacogenomics to infer large-scale drug taxonomy',
		authors: 'El-Hachem N, Gendoo DM, Soltan Ghoraie L, Safikhani Z, Smirnov P, Chung C, Deng K, Fang A, Birkwood E, Ho C, Isserlin R, Bader G, Goldenberg A, Haibe-Kains B',
		year: '2017',
		url: 'https://pubmed.ncbi.nlm.nih.gov/28314784/',
		publisher: 'Cancer Res',
		releaseDate: '2017 Mar 17',
		image: 'cancer_res_101158.jpg',
		members: [],
	},
	{
		title: 'Genomic biomarkers for precision radiation medicine',
		authors: 'Bratman SV, Milosevic MF, Liu FF, Haibe-Kains B',
		year: '2017',
		url: 'https://pubmed.ncbi.nlm.nih.gov/28495284/',
		publisher: '',
		releaseDate: '2017 May',
		image: '',
		members: [],
	},
	{
		title: 'Tissue specificity of in vitro drug sensitivity',
		authors: 'Yao F, Seyed Ali Tonekaboni SAM,  Safikhani Z, Smirnov P, El-Hachem N, Freeman M, Manem VSK, Haibe-Kains B',
		year: '2017',
		url: 'https://www.biorxiv.org/content/10.1101/085357v1.full',
		publisher: 'Biorxiv',
		releaseDate: ' 2017 July 7',
		image: 'biorxiv2.png',
		members: [],
	},
	{
		title: 'Gene isoforms as expression-based biomarkers predictive of drug response in vitro',
		authors: 'Safikhani Z, Smirnov P, Thu KL, Silvester J, Lupien M, Mak TW, Cescon D, Haibe-Kains B',
		year: '2017',
		url: 'https://pubmed.ncbi.nlm.nih.gov/29066719/',
		publisher: 'Nat Commun',
		releaseDate: '2017 Oct 24',
		image: 'ncomms.jpeg',
		members: [],
	},
	{
		title: 'Network Science in Clinical Trials: a patient-based approach',
		authors: 'Manem VSK, Salgado R, Aftimos P, Sotiriou C, Haibe-Kains B. Semin Cancer Biol',
		year: '2017',
		url: 'https://pubmed.ncbi.nlm.nih.gov/29278737/',
		publisher: 'Semin Cancer Biol',
		releaseDate: '2017 Dec 23',
		image: 'seminars_cancerbio_101016.jpg',
		members: [],
	},
];

export default PublicationData;
